/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import data.TblUser;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.User;

/**
 *
 * @author hebod
 */
public class FrmLogin extends javax.swing.JFrame {

    TblUser dUser = new TblUser();
    User actualUser = new User();
    
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTfEmail.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoginPanel = new javax.swing.JPanel();
        jLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtCreateAccount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTfEmail = new javax.swing.JTextField();
        jPfPassword = new javax.swing.JPasswordField();
        jTxtErrorEmail = new javax.swing.JLabel();
        jBtnLogin = new javax.swing.JPanel();
        jLbLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSpEmail = new javax.swing.JPanel();
        jSpPassword = new javax.swing.JPanel();
        jTxtErrorPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setSize(new java.awt.Dimension(400, 350));

        jLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        jLoginPanel.setMaximumSize(new java.awt.Dimension(400, 350));
        jLoginPanel.setMinimumSize(new java.awt.Dimension(400, 350));
        jLoginPanel.setLayout(null);

        jLogin.setBackground(new java.awt.Color(51, 51, 255));
        jLogin.setForeground(new java.awt.Color(51, 51, 255));
        jLogin.setMaximumSize(new java.awt.Dimension(100, 350));

        javax.swing.GroupLayout jLoginLayout = new javax.swing.GroupLayout(jLogin);
        jLogin.setLayout(jLoginLayout);
        jLoginLayout.setHorizontalGroup(
            jLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLoginLayout.setVerticalGroup(
            jLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jLoginPanel.add(jLogin);
        jLogin.setBounds(0, 0, 100, 350);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLoginPanel.add(jLabel1);
        jLabel1.setBounds(210, 20, 70, 40);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jLoginPanel.add(jLabel3);
        jLabel3.setBounds(140, 170, 70, 20);

        jTxtCreateAccount.setBackground(new java.awt.Color(0, 0, 0));
        jTxtCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtCreateAccount.setForeground(new java.awt.Color(0, 0, 0));
        jTxtCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTxtCreateAccount.setText("Create Account");
        jTxtCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtCreateAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTxtCreateAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTxtCreateAccountMouseExited(evt);
            }
        });
        jLoginPanel.add(jTxtCreateAccount);
        jTxtCreateAccount.setBounds(200, 310, 110, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        jLoginPanel.add(jLabel4);
        jLabel4.setBounds(140, 80, 40, 20);

        jTfEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTfEmail.setForeground(new java.awt.Color(147, 147, 147));
        jTfEmail.setText("Enter your email");
        jTfEmail.setBorder(null);
        jTfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTfEmailFocusGained(evt);
            }
        });
        jTfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTfEmailMousePressed(evt);
            }
        });
        jTfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfEmailActionPerformed(evt);
            }
        });
        jLoginPanel.add(jTfEmail);
        jTfEmail.setBounds(140, 110, 220, 30);

        jPfPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPfPassword.setForeground(new java.awt.Color(147, 147, 147));
        jPfPassword.setText("****************");
        jPfPassword.setBorder(null);
        jPfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPfPasswordFocusGained(evt);
            }
        });
        jPfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPfPasswordMousePressed(evt);
            }
        });
        jPfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPfPasswordActionPerformed(evt);
            }
        });
        jLoginPanel.add(jPfPassword);
        jPfPassword.setBounds(140, 200, 220, 30);

        jTxtErrorEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTxtErrorEmail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTxtErrorEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTxtErrorEmail.setText("xd2");
        jLoginPanel.add(jTxtErrorEmail);
        jTxtErrorEmail.setBounds(140, 150, 220, 14);

        jBtnLogin.setBackground(new java.awt.Color(51, 51, 255));
        jBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnLoginMouseExited(evt);
            }
        });

        jLbLogin.setBackground(new java.awt.Color(255, 255, 255));
        jLbLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbLogin.setText("Login");
        jLbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbLoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jBtnLoginLayout = new javax.swing.GroupLayout(jBtnLogin);
        jBtnLogin.setLayout(jBtnLoginLayout);
        jBtnLoginLayout.setHorizontalGroup(
            jBtnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jBtnLoginLayout.setVerticalGroup(
            jBtnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLoginPanel.add(jBtnLogin);
        jBtnLogin.setBounds(210, 270, 90, 30);

        jPanel1.setMaximumSize(new java.awt.Dimension(130, 2));
        jPanel1.setMinimumSize(new java.awt.Dimension(130, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLoginPanel.add(jPanel1);
        jPanel1.setBounds(140, 140, 220, 0);

        jSpEmail.setBackground(new java.awt.Color(0, 0, 0));
        jSpEmail.setMaximumSize(new java.awt.Dimension(220, 2));
        jSpEmail.setMinimumSize(new java.awt.Dimension(220, 2));
        jSpEmail.setPreferredSize(new java.awt.Dimension(220, 2));
        jSpEmail.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jSpEmailLayout = new javax.swing.GroupLayout(jSpEmail);
        jSpEmail.setLayout(jSpEmailLayout);
        jSpEmailLayout.setHorizontalGroup(
            jSpEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jSpEmailLayout.setVerticalGroup(
            jSpEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLoginPanel.add(jSpEmail);
        jSpEmail.setBounds(140, 140, 220, 2);

        jSpPassword.setBackground(new java.awt.Color(0, 0, 0));
        jSpPassword.setMaximumSize(new java.awt.Dimension(220, 2));
        jSpPassword.setMinimumSize(new java.awt.Dimension(220, 2));
        jSpPassword.setPreferredSize(new java.awt.Dimension(220, 2));

        javax.swing.GroupLayout jSpPasswordLayout = new javax.swing.GroupLayout(jSpPassword);
        jSpPassword.setLayout(jSpPasswordLayout);
        jSpPasswordLayout.setHorizontalGroup(
            jSpPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jSpPasswordLayout.setVerticalGroup(
            jSpPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLoginPanel.add(jSpPassword);
        jSpPassword.setBounds(140, 230, 220, 2);

        jTxtErrorPassword.setBackground(new java.awt.Color(255, 255, 255));
        jTxtErrorPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTxtErrorPassword.setForeground(new java.awt.Color(255, 255, 255));
        jTxtErrorPassword.setText("xd2");
        jLoginPanel.add(jTxtErrorPassword);
        jTxtErrorPassword.setBounds(140, 240, 220, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfEmailActionPerformed

    private void jTfEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTfEmailMousePressed
        if (jTfEmail.getText().equals("Enter your email")) {
            jTfEmail.setText("");
            jTfEmail.setForeground(new Color(147, 147, 147));
        }

        if (String.valueOf(jPfPassword.getPassword()).equals("")) {
            jPfPassword.setText("****************");
            jPfPassword.setForeground(new Color(147, 147, 147));
        }
    }//GEN-LAST:event_jTfEmailMousePressed

    private void jPfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPfPasswordFocusGained
        jPfPassword.setText("");
    }//GEN-LAST:event_jPfPasswordFocusGained

    private void jTfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfEmailFocusGained
        jTfEmail.setText("");
    }//GEN-LAST:event_jTfEmailFocusGained

    private void jPfPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPfPasswordMousePressed
        if (jPfPassword.getPassword().equals("****************")) {
            jPfPassword.setText("");
            jPfPassword.setForeground(new Color(147, 147, 147));
        }

        if (String.valueOf(jTfEmail.getText()).equals("")) {
            jTfEmail.setText("Enter your email");
            jTfEmail.setForeground(new Color(147, 147, 147));
        }
    }//GEN-LAST:event_jPfPasswordMousePressed

    private void jLbLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbLoginMouseEntered
        jBtnLogin.setBackground(new Color(51,86,236));
    }//GEN-LAST:event_jLbLoginMouseEntered

    private void jBtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseEntered
        
    }//GEN-LAST:event_jBtnLoginMouseEntered

    private void jBtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseExited
        
    }//GEN-LAST:event_jBtnLoginMouseExited

    private void jBtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLoginMouseClicked

        
    }//GEN-LAST:event_jBtnLoginMouseClicked

    private void jLbLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbLoginMouseExited
        jBtnLogin.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_jLbLoginMouseExited

    private void jLbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbLoginMouseClicked
        try {
            jTxtErrorEmail.setForeground(new Color(255,255,255));
            jTxtErrorEmail.setForeground(new Color(255,255,255));
            jSpEmail.setBackground(new Color(0,0,0));
            jSpPassword.setBackground(new Color(0,0,0));
            this.checkUser(jTfEmail.getText(), String.valueOf(jPfPassword.getPassword()));
        } catch (IOException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLbLoginMouseClicked

    private void jPfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPfPasswordActionPerformed

    private void jTxtCreateAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCreateAccountMouseEntered
        this.jTxtCreateAccount.setForeground(new Color(51,51,255));
    }//GEN-LAST:event_jTxtCreateAccountMouseEntered

    private void jTxtCreateAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCreateAccountMouseExited
        this.jTxtCreateAccount.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jTxtCreateAccountMouseExited

    private void jTxtCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtCreateAccountMouseClicked
        this.dispose();
        FrmCreateAccount frmCreateAccount = new FrmCreateAccount();
        frmCreateAccount.setVisible(true);
    }//GEN-LAST:event_jTxtCreateAccountMouseClicked

    private void checkUser(String email, String password) throws IOException{
        if(dUser.existUserByEmail(email)){
            actualUser = dUser.getUserByEmail(email);
            if(actualUser.getUserPassword().equals(password)){
                this.dispose();
                FrmMain main = new FrmMain(actualUser.getUserName());
                main.setVisible(true);
            }else{
                jTxtErrorPassword.setForeground(new Color(255,0,0));
                jTxtErrorPassword.setText("Invalid Password");
                jSpPassword.setBackground(new Color(255,0,0));
            }
        }else{
            jTxtErrorEmail.setText("User not found");
            jTxtErrorEmail.setForeground(new Color(255,0,0));
            jSpEmail.setBackground(new Color(255,0,0));
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLbLogin;
    private javax.swing.JPanel jLogin;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPfPassword;
    private javax.swing.JPanel jSpEmail;
    private javax.swing.JPanel jSpPassword;
    private javax.swing.JTextField jTfEmail;
    private javax.swing.JLabel jTxtCreateAccount;
    private javax.swing.JLabel jTxtErrorEmail;
    private javax.swing.JLabel jTxtErrorPassword;
    // End of variables declaration//GEN-END:variables
}
